feat-6
fabricadesoftware-ifc/fabricaHackathon-frontend pull request #20
Opened 2024-07-11 20:03 UTC by Joaovictor23t4

### Test Plan for 
#### Actions Taken:
- Created API and state management for Alunos
- Fix baseURL of all Cursos and Turmas calls
- Tested each Alunos API call

#### Required Tests:
1. Test each Alunos API call and verify that data is returned correctly

#### Tested Browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari
- [ ] Opera

#### Closing Keywords:
- closes #6

#### Notes:

2024-07-11 21:40 UTC, Hiansdt requested changes
Remove unused logs.

Tip: Use the native search function of VSCode to search for specific lines like logs throughout the whole project.

2024-07-11 21:40 UTC, Hiansdt commented on src/views/HomeView.vue
>  <script setup>
Remover linhas comentadas

2024-07-12 15:13 UTC, Joaovictor23t4 commented on src/views/HomeView.vue
>  <script setup>
Removed!

2024-07-14 14:46 UTC, Hiansdt requested changes
OK

2024-07-14 19:19 UTC, Hiansdt approved these changes
OK

2024-07-14 19:20 UTC, merged